### ISSUE TITLE
Deleting objects does not persist

### ISSUE THREAD

**Issue by connersimmons** [srmds/CoreData-CRUD-Swift-2.0-example#18]
After deleting objects (Events in your case), then closing and restarting the application, the objects that I deleted still show up. I was wondering if I was doing something wrong, since I am deleting my objects just as you are deleting your Event objects.

**Comment by srmds** [comment]
@connersimmons Thanks for catching that bug. It looks like that the changes from the main context aren't saved.

A solution would be to call `self.persistenceManager.mergeWithMainContext()`,
that causes the changes (the deletion) in the mainContext to actually save the changes, which will actually delete the stored objects from the datastore. Seems to me i forgot to actually do the merge/save call.

Try this:

```
func deleteAllEvents() {
       let retrievedItems = getAllEvents()

       //Delete all event items from persistance layer
       for item in retrievedItems {
           self.mainContextInstance.deleteObject(item)
       }

      //Merge /save changes on mainContext 
      self.persistenceManager.mergeWithMainContext()

      self.postUpdateNotification()
}
```

**Comment by connersimmons** [comment]
@srmds I thought that may do the trick. I thought I had tried that, but I guess I didn't. Made that change to my code and it seems to be working great. Thanks for the quick response!
