### ISSUE TITLE
mergeWithMainContext crashes if dataset is very large

### ISSUE THREAD

**Issue by rkheir** [srmds/CoreData-CRUD-Swift-2.0-example#23]
Dataset I used has 100,000 json records with two words per record. Size was ~8MB. This causes the app to crashe each time at persistenceManager.mergeWithMainContext.

**Comment by srmds** [comment]
@rkheir Thanks for the heads up, will investigate and report back

**Comment by rkheir** [comment]
One can merge more often of course by doing something like:

  if count % 20 == 0 || count == max - 1 {
          self.persistenceManager.saveWorkerContext(minionManagedObjectContextWorker)
        }
