### ISSUE TITLE
Add support for Swift 4.0

### ISSUE THREAD

**Issue by srmds** [srmds/CoreData-CRUD-Swift-2.0-example#25]
Migrate project to support Swift 4.0 @Silvest89 Interested in picking this up? :)

**Comment by srmds** [comment]
@silviavanwingerden Interested in picking this up?

**Comment by Silvest89** [comment]
I can pick it up

**Comment by srmds** [comment]
@Silvest89 Great! Maybe @silviavanwingerden also wants to help, maybe you or silvia have some suggestions to extend the current code base with better functionality, or tests .. :)
